package com.team.proba.igwp.model

case class Example(
  gameTimeMS: Long,
  champion1Id: Int,
  champion2Id: Int,
  champion3Id: Int,
  champion4Id: Int,
  champion5Id: Int,
  champion6Id: Int,
  champion7Id: Int,
  champion8Id: Int,
  champion9Id: Int,
  champion10Id: Int,
  baronKillsTeam1: Int,
  baronKillsTeam2: Int,
  dragonKillsTeam1: Int,
  dragonKillsTeam2: Int,
  towerKillsTeam1: Int,
  towerKillsTeam2: Int,
  goldTeam1: Int,
  goldTeam2: Int,
  killsTeam1: Int,
  killsTeam2: Int,
  deathsTeam1: Int,
  deathsTeam2: Int,
  assistsTeam1: Int,
  assistsTeam2: Int,
  champLvlsTeam1: Int,
  champLvlsTeam2: Int,
  minionKillsTeam1: Int,
  minionKillsTeam2: Int,
  minLeagueTeam1: String,
  minLeagueTeam2: String,
  maxLeagueTeam1: String,
  maxLeagueTeam2: String,
  winner: Int
)
